name: ssh_customer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  razorpay_flutter: ^1.3.7
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  image_cropper: ^8.0.1
  
  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utilities
 
  uuid: ^4.4.0
  url_launcher: ^6.2.1
  
  # Notifications
  fluttertoast: ^8.2.10
  firebase_storage: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ssh_logo.png
    - assets/icons/app_icon.png
    - assets/images/logincover.png
    - assets/images/resort.png
    - assets/images/coliving.png
    - assets/images/hotel.png
    - assets/images/logowhite.png.jpeg